language: java

jdk:
  - oraclejdk9

addons:
  apt:
    package:
    - junit4
    - libmockito-java

script:
  - mkdir -p bin
  - javac -classpath /usr/share/java/junit4.jar:/usr/share/java/mockito-core.jar src/PriorityQueueTest.java -d bin
  - cd bin ; java -classpath .:/usr/share/java/junit4.jar org.junit.runner.JUnitCore PriorityQueueTest
